### ISSUE TITLE
bug hunting

### ISSUE THREAD

**Issue by cmagness** [cmagness/spectrAOD#13]
this issue is for other bugs i find during the original test run

- [x] another `IndexError`:
Traceback (most recent call last):
  File "measure_aod.py", line 166, in <module>
    status = main()
  File "measure_aod.py", line 153, in main
    spectrum = continuum_fit(spectrum)
  File "measure_aod.py", line 112, in continuum_fit
    spectrum, linear_fits = spectrum.calculate_fits(continuum)
  File "/user/cmagness/fermi/code/spectrAOD/spectrAOD/format_data.py", line 399, in calculate_fits
    self.norm_flux = lists[1]  # list of normalized fluxes
IndexError: list index out of range

**Comment by cmagness** [comment]
- [x] `ValueError`:
Traceback (most recent call last):
  File "measure_aod.py", line 169, in <module>
    status = main()
  File "measure_aod.py", line 159, in main
    spectrum = measure(args, spectrum)
  File "measure_aod.py", line 128, in measure
    helper = Helper(spectrum, indices)
  File "/user/cmagness/fermi/code/spectrAOD/spectrAOD/format_data.py", line 52, in __init__
    for idx, velocity in spectrum.velocity:
ValueError: too many values to unpack (expected 2)

**Comment by cmagness** [comment]
- [x] `IndexError`:
Traceback (most recent call last):
  File "measure_aod.py", line 169, in <module>
    status = main()
  File "measure_aod.py", line 159, in main
    spectrum = measure(args, spectrum)
  File "measure_aod.py", line 128, in measure
    helper = Helper(spectrum, indices)
  File "/user/cmagness/fermi/code/spectrAOD/spectrAOD/format_data.py", line 53, in __init__
    truncated_dict["velocity"].append(velocity[indices[0]:indices[1]])
IndexError: list index out of range

**Comment by cmagness** [comment]
- [x] `AttributeError`:
Traceback (most recent call last):
  File "measure_aod.py", line 169, in <module>
    status = main()
  File "measure_aod.py", line 159, in main
    spectrum = measure(args, spectrum)
  File "measure_aod.py", line 131, in measure
    helper.fix_negatives()
  File "/user/cmagness/fermi/code/spectrAOD/spectrAOD/format_data.py", line 85, in fix_negatives
    in subflux])
  File "/user/cmagness/fermi/code/spectrAOD/spectrAOD/format_data.py", line 84, in <listcomp>
    val)] * 0.01 if val < 0 else val for val
AttributeError: 'numpy.ndarray' object has no attribute 'index'

**Comment by cmagness** [comment]
- [x] `ValueError`:
Traceback (most recent call last):
  File "measure_aod.py", line 169, in <module>
    status = main()
  File "measure_aod.py", line 159, in main
    spectrum = measure(args, spectrum)
  File "measure_aod.py", line 133, in measure
    helper.calculate_aod()
  File "/user/cmagness/fermi/code/spectrAOD/spectrAOD/format_data.py", line 95, in calculate_aod
    flux_err = self.error / subflux
ValueError: operands could not be broadcast together with shapes (1,0) (80,) 

`self.error` needs to be `self.error[idx]` but furthermore that is empty and needs investigating further up to see why. at this point, `spectrum.norm_error` and `spectrum.norm_flux` are partially (if not all) full of -0 values, which makes no sense.

**Comment by cmagness** [comment]
- [x] `KeyError`:
Traceback (most recent call last):
  File "measure_aod.py", line 169, in <module>
    status = main()
  File "measure_aod.py", line 159, in main
    spectrum = measure(args, spectrum)
  File "measure_aod.py", line 135, in measure
    helper.calculate_acd()
  File "/user/cmagness/fermi/code/spectrAOD/spectrAOD/format_data.py", line 123, in calculate_acd
    subacd["acd"]
KeyError: 'acd'

**Comment by cmagness** [comment]
- [x] `TypeError`:
Traceback (most recent call last):
  File "measure_aod.py", line 169, in <module>
    status = main()
  File "measure_aod.py", line 159, in main
    spectrum = measure(args, spectrum)
  File "measure_aod.py", line 137, in measure
    helper.calculate_ew()
  File "/user/cmagness/fermi/code/spectrAOD/spectrAOD/format_data.py", line 158, in calculate_ew
    ew_row = (self.ions["wv"][idx] / C) * self.delta * (
TypeError: can't multiply sequence by non-int of type 'float'

**Comment by cmagness** [comment]
- [x] `TypeError`:
Traceback (most recent call last):
  File "measure_aod.py", line 169, in <module>
    status = main()
  File "measure_aod.py", line 159, in main
    spectrum = measure(args, spectrum)
  File "measure_aod.py", line 139, in measure
    helper.significance()
  File "/user/cmagness/fermi/code/spectrAOD/spectrAOD/format_data.py", line 189, in significance
    sig_boolean.extend((subdict["ew"] >= 3.0 * subdict["error"]))
TypeError: 'numpy.bool_' object is not iterable

**Comment by cmagness** [comment]
- [x] `KeyError`:
Traceback (most recent call last):
  File "measure_aod.py", line 169, in <module>
    status = main()
  File "measure_aod.py", line 161, in main
    spectrum.generate_table(args.vel_min, args.vel_max)
  File "/user/cmagness/fermi/code/spectrAOD/spectrAOD/format_data.py", line 441, in generate_table
    "ION": self.ions[idx],
KeyError: 0

**Comment by cmagness** [comment]
- [x] `TypeError`:
Traceback (most recent call last):
  File "measure_aod.py", line 169, in <module>
    status = main()
  File "measure_aod.py", line 161, in main
    spectrum.generate_table(args.vel_min, args.vel_max)
  File "/user/cmagness/fermi/code/spectrAOD/spectrAOD/format_data.py", line 455, in generate_table
    "DETECTION": self.detection[idx]
  File "/Users/cmagness/miniconda3/envs/spectraod/lib/python3.5/site-packages/pandas/core/frame.py", line 6177, in append
    raise TypeError('Can only append a Series if ignore_index=True'
TypeError: Can only append a Series if ignore_index=True or if the Series has a name

**Comment by cmagness** [comment]
runs for single ion case. errors seem off, will open a new issue to investigate that

**Comment by cmagness** [comment]
doublet bug

- [x] `ValueError`:
Traceback (most recent call last):
  File "measure_aod.py", line 169, in <module>
    status = main()
  File "measure_aod.py", line 159, in main
    spectrum = measure(args, spectrum)
  File "measure_aod.py", line 139, in measure
    helper.significance()
  File "/user/cmagness/fermi/code/spectrAOD/spectrAOD/format_data.py", line 193, in significance
    minimum = min(subflux / self.continuum[idx])
ValueError: min() arg is an empty sequence

well. everything is empty. this is going to need investigating from the beginning

edit: this is because `find_indices()` is only finding the same index for the entire window. so, effectively, a window size of 0.

edit: this is because the ions i was searching for were out of range of the spectrum. added handling for that scenario.
